*******************************************************************************************
*******************************************************************************************
*******************************************************************************************
**               I N F O R M   B O X   F O R   H P 4 8                                   **
*******************************************************************************************
*******************************************************************************************
*******************************************************************************************

*******************************************************************************************
* Some Field types constants
*******************************************************************************************
( Do not modify any of these constants )
DEFINE IfFieldTypeText ONE                            
* DEFINE IfFieldTypeChooseEdit TWO                    ( not for HP48 )
DEFINE IfFieldTypeAlg THREE
DEFINE IfFieldTypeChoose TWELVE
*DEFINE IfFieldTypeExtended TWENTYTHREE       ( not for HP48 )
DEFINE IfFieldTypeCheck THIRTYTWO
* DEFINE IfFieldTypeLabelChoose THIRTYTHREE    ( not for HP48 )

*******************************************************************************************
* Some object types constants
*******************************************************************************************
( Do not modify any of these constants )
DEFINE IfObReal ZERO
DEFINE IfObCmp ONE
DEFINE IfObStr TWO
DEFINE IfObArray THREE
DEFINE IfObList FIVE
DEFINE IfObId SIX
DEFINE IfObLocal SEVEN
DEFINE IfObPrg EIGHT
DEFINE IfObAlg NINE
DEFINE IfObHxs TEN
DEFINE IfObUnit THIRTEEN
DEFINE IfObInt TWENTY                ( changed for HP48, was zint=BINT255d for HP49)
*******************************************************************************************
* BINT Defines
*******************************************************************************************
DEFINE BINT0 ZERO
DEFINE BINT1 ONE
DEFINE BINT2 TWO
DEFINE BINT3 THREE
DEFINE BINT4 FOUR
DEFINE BINT5 FIVE
DEFINE BINT6 SIX
DEFINE BINT7 SEVEN
DEFINE BINT8 EIGHT
DEFINE BINT9 NINE
DEFINE BINT10 TEN
DEFINE BINT11 ELEVEN
DEFINE BINT12 TWELVE
DEFINE BINT13 THIRTEEN
DEFINE BINT14 FOURTEEN
DEFINE BINT15 FIFTEEN
DEFINE BINT16 SIXTEEN
DEFINE BINT17 SEVENTEEN
DEFINE BINT18 EIGHTEEN
DEFINE BINT19 NINETEEN
DEFINE BINT20 TWENTY
DEFINE BINT21 TWENTYONE
DEFINE BINT22 TWENTYTWO
DEFINE BINT23 TWENTYTHREE
DEFINE BINT24 TWENTYFOUR
DEFINE BINT25 TWENTYFIVE
DEFINE BINT26 TWENTYSIX
DEFINE BINT27 TWENTYSEVEN
DEFINE BINT28 TWENTYEIGHT
DEFINE BINT29 TWENTYNINE
DEFINE BINT30 THIRTY
DEFINE BINT31 THIRTYONE
DEFINE BINT32 THIRTYTWO
DEFINE BINT33 THIRTYTHREE
DEFINE BINT34 THIRTYFOUR
DEFINE BINT35 THIRTYFIVE
DEFINE BINT36 THIRTYSIX
DEFINE BINT37 THIRTYSEVEN
DEFINE BINT38 THIRTYEIGHT
DEFINE BINT39 THIRTYNINE
DEFINE BINT40 FORTY
DEFINE BINT41 FORTYONE
DEFINE BINT42 FORTYTWO
DEFINE BINT43 FORTYTHREE
DEFINE BINT44 FORTYFOUR
DEFINE BINT45 FORTYFIVE
DEFINE BINT46 FORTYSIX
DEFINE BINT47 FORTYSEVEN
DEFINE BINT48 FORTYEIGHT
DEFINE BINT49 FORTYNINE
DEFINE BINT50 FIFTY
DEFINE BINT51 FIFTYONE
DEFINE BINT52 FIFTYTWO
DEFINE BINT53 FIFTYTHREE
DEFINE BINT54 FIFTYFOUR
DEFINE BINT55 FIFTYFIVE
DEFINE BINT56 FIFTYSIX
DEFINE BINT57 FIFTYSEVEN
DEFINE BINT58 FIFTYEIGHT
DEFINE BINT59 FIFTYNINE
DEFINE BINT60 SIXTY
DEFINE BINT61 SIXTYONE
DEFINE BINT62 SIXTYTWO
DEFINE BINT63 SIXTYTHREE
DEFINE BINT64 SIXTYFOUR
DEFINE BINT65 BINT_65d
DEFINE BINT66 FOURTWO
DEFINE BINT67 FOURTHREE
DEFINE BINT68 SIXTYEIGHT
DEFINE BINT69 FOURFIVE
DEFINE BINT70 SEVENTY
DEFINE BINT71 71
DEFINE BINT72 72
DEFINE BINT73 73
DEFINE BINT74 SEVENTYFOUR
DEFINE BINT75 75
DEFINE BINT76 76
DEFINE BINT77 77
DEFINE BINT78 78
DEFINE BINT79 SEVENTYNINE
DEFINE BINT80 EIGHTY
DEFINE BINT81 EIGHTYONE
DEFINE BINT82 82
DEFINE BINT83 FIVETHREE
DEFINE BINT84 FIVEFOUR
DEFINE BINT85 85
DEFINE BINT86 FIVESIX
DEFINE BINT87 87
DEFINE BINT88 88
DEFINE BINT89 89
DEFINE BINT90 90
DEFINE BINT91 BINT_91d
DEFINE BINT92 92
DEFINE BINT93 93
DEFINE BINT94 94
DEFINE BINT95 95
DEFINE BINT96 BINT_96d
DEFINE BINT97 97
DEFINE BINT98 98
DEFINE BINT99 99
DEFINE BINT100 ONEHUNDRED
DEFINE BINT101 101
DEFINE BINT102 102
DEFINE BINT103 103
DEFINE BINT104 104
DEFINE BINT105 105
DEFINE BINT106 106
DEFINE BINT107 107
DEFINE BINT108 108
DEFINE BINT109 109
DEFINE BINT110 110
DEFINE BINT111 111
DEFINE BINT112 112
DEFINE BINT113 113
DEFINE BINT114 114
DEFINE BINT115 BINT_115d
DEFINE BINT116 BINT_116d
DEFINE BINT117 117
DEFINE BINT118 118
DEFINE BINT119 119
DEFINE BINT120 120
DEFINE BINT121 121
DEFINE BINT122 BINT_122d
DEFINE BINT123 123
DEFINE BINT124 124
DEFINE BINT125 125
DEFINE BINT126 126
DEFINE BINT127 127
DEFINE BINT128 BINT80h
DEFINE BINT129 129
DEFINE BINT130 BINT_130d
DEFINE BINT131 BINT_131d
DEFINE BINT132 132
DEFINE BINT133 133
DEFINE BINT134 134
DEFINE BINT135 135
DEFINE BINT136 136
DEFINE BINT137 137
DEFINE BINT138 138
DEFINE BINT139 139
*
*  CHECKING FOR EMPTY FIELDS
*
*  HP48 Inform returns a MINUSONE for empty fields
*  HP49 Inform returns a xNOVAL for empty fields
*  You might want to check for missing values with something, but the code
*  would be different on the two calcs.
*
*  In Suprom48, I have defined NOVAL EQU (same as MINUSONE)
*  In Suprom49, I have defined NOVAL EQU (same as xNOVAL)
*  Now a common test for missing field could be  xxxx NOVAL EQ
*  This works unless we run a DoInputForm on the HP49!! (get a MINUSONE on the 49 when we expected xNOVAL)
*  The sample code below returns a #1 for valid field, #0 for empty field.
*  This code works in all 3 cases!
*
*  DUP MINUSONE EQ ITE :: DROP #0 ; :: NOVAL EQ ITE #0 #1 ;
