set MATLAB=C:\MATLAB7
"%MATLAB%\rtw\bin\win32\gmake" -f Subsystem.mk ADD_MDL_NAME_TO_GLOBALS=1 MODELLIB=Subsystemlib.lib SHARED_SRC= SHARED_SRC_DIR= SHARED_BIN_DIR= MODELREF_LINK_LIBS= SHARED_LIB= RELATIVE_PATH_TO_ANCHOR=.. MODELREF_TARGET_TYPE=NONE
